program cad_popd;

uses spr2_ein;

begin
  sprachtabellenkopf(
                    +'EN'
                    +'DE'
                    +'NL' (* thanks to Jan van der Heide *)
                    +'RU' (* thanks to Yuri Proniakin    *)
                    +'IT' (* thanks to Gabriele Gamba    *)
                    +'TW' (* thanks to Ming-Lung Cheng   *)
                    +'FR' (* thanks to Guillaume Gay     *)
                    +'ES' (* thanks to Alfredo Fern†ndez *)
                    +''
                    +''
                    +''
                    +'');

  sprach_eintrag12('_press_a_key_to_continue_',
                   ' <press a key to continue> ',
                   ' <Weiter mit Tastendruck> ',
                   ' <Druk op een toets om verder te gaan> ',
                   ' <ç†¶¨®‚• ´Ó°„Ó ™´†¢®Ë„ §´Ô Ø‡Æ§Æ´¶•≠®Ô> ',
                   ' <premere un tasto per continuare> ',
                   ' <´ˆ•Ù∑N¡‰ƒ~ƒÚ> ',
                   ' <tapez sur une touche pour continuer> ',
                   ' <pulse una tecla para continuar> ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('_press_a_key_to_quit_',
                   ' <press a key to quit> ',
                   ' <Abbruch mit Tastendruck> ',
                   ' <Druk op een toets om te stoppen> ',
                   ' <ç†¶¨®‚• ´Ó°„Ó ™´†¢®Ë„ §´Ô ¢ÎÂÆ§†> ',
                   ' <premere un tasto per interrompere> ',
                   ' <´ˆ•Ù∑N¡‰¬˜∂}> ',
                   ' <tapez sur une touche pour quitter> ',
                   ' <pulse una tecla para salir> ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_21',
                   ' (not ready)',
                   ' (nicht bereit)',
                   ' (niet gereed) ',
                   ' (≠• £Æ‚Æ¢)',
                   ' (non pronto)',
                   ' (©|•º∑«≥∆¶n)',
                   ' (non pràt)',
                   ' (no est† preparado)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_32',
                   ' (in use)',
                   ' (von anderem Prozess benutzt)',
                   ' (in gebruik) ',
                   ' (®·ØÆ´Ïß„•‚·Ô)',
                   ' (in uso)',
                   ' (®œ•Œ§§)',
                   ' (en cours d''utilisation)',
                   ' (ya se est† utilizando)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_50',
                   ' (not supported by network software)',
                   ' (vom Netzlaufwerk nicht unterstÅtzt)',
                   ' (niet ondersteunt door netwerk programmatuur) ',
                   ' (≠• ØÆ§§•‡¶®¢†•‚·Ô ·•‚•¢Î¨® ™Æ¨ØÆ≠•≠‚†¨®)',
                   ' (non supportato dal software di rete)',
                   ' (∫Ù∏Ù≥n≈È§£§‰¥©)',
                   ' (non pris en charge par le logiciel rÇseau)',
                   ' (no soportado por el software de red)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_107',
                   ' (no media)',
                   ' (kein DatentrÑger eingelegt)',
                   ' (geen gegevensdrager) ',
                   ' (≠•‚ ≠Æ·®‚•´Ô)',
                   ' (no media)',
                   ' (µL¥C≈È∏À∏m)',
                   ' (pas de mÇdia)',
                   ' (unidad vac°a)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_108',
                   ' (in use)',
                   ' (noch Dateien offen)',
                   ' (in gebruik) ',
                   ' (®·ØÆ´Ïß„•‚·Ô)',
                   ' (in uso)',
                   ' (®œ•Œ§§)',
                   ' (en cours d''utilisation)',
                   ' (ya se est† utilizando)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_13',
                   ' (invalid data)',
                   ' (ungÅltige Daten)',
                   ' (verkeerde gegevens) ',
                   ' (≠•¢•‡≠Î• §†≠≠Î•)',
                   ' (dati non validi)',
                   ' (µLÆƒ™∫∏ÍÆ∆)',
                   ' (donnÇes incorrectes)',
                   ' (datos no v†lidos)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_217',
                   ' (zombie process)',
                   ' (zombie process)',
                   ' (zombie proces) ',
                   ' (ßÆ¨°®)',
                   ' (processo zombi)',
                   ' (ºo§Ó™∫∂iµ{)',
                   ' (processus "zombie")',
                   ' (proceso zombi)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_303',
                   ' (invalid procid)',
                   ' (ungÅltige Prozesskennung)',
                   ' (verkeerd procid) ',
                   ' (≠•¢•‡≠Î© àÑ Ø‡ÆÊ•··†)',
                   ' (ID processo non valida)',
                   ' (µLÆƒ™∫∂iµ{ ID)',
                   ' (ID de processus incorrect)',
                   ' (identificador de proceso no v†lido)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_305',
                   ' (not descendant)',
                   ' (Kein Unterprozess)',
                   ' (geen afgeleide) ',
                   ' (≠• Ô¢´Ô•‚·Ô ØÆ‚Æ¨™Æ¨)',
                   ' (nessun sottoprocesso)',
                   ' (´D§l•N)',
                   ' (non descendant)',
                   ' (no es un descendiente)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_87',
                   ' (invalid parameter)',
                   ' (ungÅltiger Parameter)',
                   ' (verkeerde parameter) ',
                   ' (≠•¢•‡≠Î© Ø†‡†¨•‚‡)',
                   ' (parametro non valido)',
                   ' (µLÆƒ™∫∞—º∆)',
                   ' (paramätre incorrect)',
                   ' (par†metro no v†lido)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('err_99',
                   ' (unit already used by other application)',
                   ' (Einheit wird schon von anderer Anwendung benutzt)',
                   ' (eenheid al in gebruik door andere applicatie) ',
                   ' („·‚‡Æ©·‚¢Æ „¶• ®·ØÆ´Ïß„•‚·Ô §‡„£®¨ Ø‡®´Æ¶•≠®•¨)',
                   ' (unitÖ in uso da parte di un''altra applicazione)',
                   ' (§w¶≥®‰•L¿≥•Œµ{¶°®œ•Œ¶π≥Ê¶Ï)',
                   ' (unitÇ en cours d ''utilisation par une autre application)',
                   ' (la unidad ya est† siendo utilizada por otra aplicaci¢n)',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_open_volume',
                   ' Can not open volume %1:',
                   ' Kann Laufwerk %1: nicht îffnen',
                   ' Kan volume %1: niet openen ',
                   ' ç•¢Æß¨Æ¶≠Æ Æ‚™‡Î‚Ï ‚Æ¨ %1:',
                   ' Impossibile aprire il volume %1:',
                   ' µL™k∂}±“Æe≈È %1:',
                   ' Ouverture impossible du volume %1:',
                   ' No se puede abrir el volumen %1:',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_lock_volume',
                   ' Can not lock volume %1:',
                   ' Kann Laufwerk %1: nicht sperren',
                   ' Kan volume %1: niet blokkeren',
                   ' ç•¢Æß¨Æ¶≠Æ ß†°´Æ™®‡Æ¢†‚Ï ‚Æ¨ %1:',
                   ' Impossibile bloccare il volume %1:',
                   ' µL™k¬Í¶ÌÆe≈È %1:',
                   ' Verrouillage impossible du volume %1:',
                   ' No se puede bloquear el volumen %1:',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Unmounted',
                   ' Unmounted %1: successful.',
                   ' Laufwerk %1: erfolgreich abgezogen.',
                   ' Loskoppelen %1: succesvol.',
                   ' íÆ¨ %1: ‡†ß¨Æ≠‚®‡Æ¢†≠.',
                   ' Volume %1: smontato con successo.',
                   ' ¶®•\®¯∏¸ %1:°C',
                   ' Volume %1: dÇmontÇ avec succäs.',
                   ' Volumen %1: desmontado satisfactoriamente.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Beginformat_for_failed',
                   ' Beginformat for %1: failed',
                   ' Die Funktion Beginformat fÅr Laufwerk %1: schlug fehl',
                   ' De functie Beginformat voor station %1: is niet gelukt',
                   ' ë°Æ© ‡†ß¨Æ≠‚®‡Æ¢†≠®Ô ‚Æ¨† %1:',
                   ' Funzione Beginformat su volume %1: fallita',
                   ' ±“©lÆÊ¶°§∆ %1: •¢±—',
                   ' êchec de la fonction Beginformat sur volume %1:',
                   ' La funci¢n Beginformat ha fallado en %1:',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Redetermine_media_for_failed',
                   ' Redetermine media for %1: failed',
                   ' Neuerkennung des Dateisystems fÅr %1: schlug fehl',
                   ' Nieuwe herkenning media voor %1: is niet gelukt',
                   ' ë°Æ© ØÆ¢‚Æ‡≠Æ£Æ ÆØ‡•§•´•≠®Ô ≠Æ·®‚•´Ô ‚Æ¨† %1:',
                   ' Identificazione file system %1: fallita',
                   ' ≠´∑s∞ª¥˙¥C≈È∏À∏m %1°G•¢±—',
                   ' êchec Ö l''identification du mÇdia pour %1:',
                   ' No se pudo volver a examinar %1:',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Remounted_successful',
                   ' Remounted %1: successful.',
                   ' Laufwerk %1: wurde erfolgreich angesteckt.',
                   ' Station %1: succesvol.',
                   ' íÆ¨ %1: ·¨Æ≠‚®‡Æ¢†≠.',
                   ' Volume %1: rimontato con successo.',
                   ' ¶®•\≠´∑s±æ∏¸ %1°G',
                   ' Volume %1: remontÇ avec succäs.',
                   ' El volumen %1: ha vuelto a montarse satisfactoriamente.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('PrfQueryProfile_failed_error',
                   ' PrfQueryProfile failed, error=',
                   ' PrfQueryProfile schlug fehl, Fehlerkode=',
                   ' PrfQueryProfile is niet gelukt, foutcode=',
                   ' ë°Æ© PrfQueryProfile, ÆË®°™†=',
                   ' PrfQueryProfile fallito, errore=',
                   ' PrfQueryProfile •¢±—°Aø˘ª~=',
                   ' êchec de PrfQueryProfile, erreur=',
                   ' Error en PrfQueryProfile, c¢digo de error=',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('PrfReset_failed_error',
                   ' PrfReset failed, error=',
                   ' PrfReset schlug fehl, Fehlerkode=',
                   ' PrfReset is niet gelukt, foutcode=',
                   ' ë°Æ© PrfReset, ÆË®°™†=',
                   ' PrfReset fallito, errore=',
                   ' PrfReset •¢±—°Aø˘ª~=',
                   ' êchec de PrfReset, erreur=',
                   ' Error en PrfReset, c¢digo de error=',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('prfreset_Success',
                   ' Success.',
                   ' Erfolgreich zurÅckgesetzt.',
                   ' Succesvol.',
                   ' ì·Ø•Ë≠Æ.',
                   ' Successo.',
                   ' ¶®•\°C',
                   ' RÇussi.',
                   ' Hecho.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Failed',
                   ' Failed',
                   ' Fehlgeschlagen',
                   ' Niet gelukt',
                   ' ë°Æ©',
                   ' Non eseguito',
                   '•¢±—',
                   ' êchec',
                   ' Error.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('xf86sup_sys_not_loaded_hard_kill_not_available',
                   ' xf86sup.sys not loaded, hard kill not available.',
                   ' xf86sup.sys ist nicht geladen, heftiges Prozessende nicht verfÅgbar.',
                   ' xf86sup.sys is niet geladen, geforceerd afsluiten is niet beschikbaar.',
                   ' xf86sup.sys ≠• ß†£‡„¶•≠, "¢Î·Ë†Ô ¨•‡†" ≠• §Æ·‚„Ø≠†.',
                   ' xf86sup.sys non caricato, impossibile forzare la chiusura del processo.',
                   ' µL™k≈™®˙ xf86sup.sys°A¨G§£Ø‡®œ•Œ±j®Ó√ˆ≥¨°C',
                   ' xf86sup.sys non chargÇ, interruption forcÇe (hard kill) non disponible.',
                   ' xf86sup.sys no est† cargado, no se puede forzar el cierre del proceso.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Trying_DosKillProcess_',
                   ' Trying DosKillProcess ...',
                   ' Versuche es mit DosKillProcess ...',
                   ' Probeer het met DosKillProcess ...',
                   ' è‡Æ°„•¨ DosKillProcess...',
                   ' Cerco di chiudere il processo con DosKillProcess ...',
                   ' •øπ¡∏’ DosKillProcess ...',
                   ' Tentative DosKillProcess...',
                   ' Intentando DosKillProcess...',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Inv__',
                   'Inv. ',
                   'Unsi.',
                   'Inv.',
                   'ë™‡.',
                   'Inv. ',
                   'Inv. ',
                   'Inv. ',
                   'Inv. ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Esc_exit_R_refresh_C_Close_K_kill_process_H_hard_kill_',
               // this is the menu line. make it shorter than 80 chars, ` does not count
               //   12345678901234567890123456789012345678901234567890123456789012345678901234567890
               //            11111111112222222222333333333344444444445555555555666666666677777777778            keys
                   '`Esc`=exit  `f`ilter  `r`efresh  `C`lose  `k`ill process  `h`ard kill  > ',                 //FRCKH
                   '`Esc`=Ende  `F`ilter  `n`eu  `S`chlie·en  `P`rozessende  `h`eftiges Prozessende > ',        //FNSPH
                   '`Esc`=Einde  `F`ilter  `N`ieuw  `S`luiten  `A`fsluiten proces  F`o`rceer proces > ',        //FNSAO
                   '`Esc`=ÇÎÂÆ§  `A`=î®´Ï‚‡  `J`=é°≠Æ¢®‚Ï  `P`=á†™‡Î‚Ï  `E`=ì°®‚Ï  `D`=ÇÎ·Ë†Ô ¨•‡†  > ',        //AJPED
                   '`Esc`=esci  `f`iltra  `a`ggiorna  `c`hiudi  `t`ermina processo  forza c`h`iusura proc. > ', //FACTH
                   '`Esc`=¬˜∂}  `F`=πL¬o  `R`=•ﬂßY¥_∑s  `C`=√ˆ≥¨  `K`=√ˆ≥¨∂iµ{  `H`=±j®Ó√ˆ≥¨  > ',              //FRCKH
               //  '`êchp`=Quitter  `F`iltrer  `R`ÇgÇnÇrer  `C`=fermer  `I`nterrup. proc.  `Z`igouiller > ',    //FRCIZ
                   '`êchap`=Quitter  `F`iltrer  `R`afraichir  `C`=fermer  `I`nterrompre proc.  `Z`igouiller > ',//FRCIZ
                   '`Esc`=Salir  `F`iltrar  `R`enovar  `C`errar  `M`atar proceso  `H`ard kill > ',//FRCMH
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('processlist_key_filter',
                   'F',
                   'F',
                   'F',
                   'A', (* î *)
                   'F',
                   'F',
                   'F',
                   'F',
                   '',
                   '',
                   '',
                   '');
  sprach_eintrag12('processlist_key_refresh',
                   'R',
                   'N',
                   'N',
                   'J', (* é *)
                   'A',
                   'R',
                   'R',
                   'R',
                   '',
                   '',
                   '',
                   '');
  sprach_eintrag12('processlist_key_close',
                   'C',
                   'S',
                   'S',
                   'P', (* á *)
                   'C',
                   'C',
                   'C',
                   'C',
                   '',
                   '',
                   '',
                   '');
  sprach_eintrag12('processlist_key_kill',
                   'K',
                   'P',
                   'A',
                   'E', (* ì *)
                   'T',
                   'K',
                   'I',
                   'M',
                   '',
                   '',
                   '',
                   '');
  sprach_eintrag12('processlist_key_hardkill',
                   'H',
                   'H',
                   'O',
                   'D', (* Ç *)
                   'H',
                   'H',
                   'Z',
                   'H',
                   '',
                   '',
                   '',
                   '');


  sprach_eintrag12('process_id_or_name_',
                   'process id or name > ',
                   'Prozesskennung oder -Name > ',
                   'Proces id of naam > ',
                   'àÑ ®´® ®¨Ô Ø‡ÆÊ•··† > ',
                   'ID o nome processo > ',
                   '∂iµ{ id ©Œ¶W∫Ÿ> ',
                   'ID ou nom de processus',
                   'ID o nombre del proceso > ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('_not_found',
                   ' not found.',
                   ' wurde nicht gefunden.',
                   ' niet gevonden.',
                   ' ≠• ≠†©§•≠.',
                   ' non trovato.',
                   ' ß‰§£®Ï°C',
                   ' non trouvÇ.',
                   ' no hallado.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('_Exec_DosError',
                   ' Executing the program failed',
                   ' AusfÅhren des Programmes schlug fehl',
                   ' Uitvoeren van het programma is niet gelukt',
                   ' ë°Æ© ¢ÎØÆ´≠•≠®Ô Ø‡Æ£‡†¨¨Î',
                   ' Esecuzione del programma fallita',
                   ' ∞ı¶Êµ{¶°•¢±—',
                   ' êchec Ö l''exÇcution du programme',
                   ' Error al ejecutar el programa',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('_Exec_ExitCode',
                   ' Returcode=',
                   ' RÅckkehrwert=',
                   ' Foutcode=',
                   ' äÆ§ ¢Æß¢‡†‚†=',
                   ' Codice uscita=',
                   ' ™¶^ΩX=',
                   ' CodeRetour=',
                   ' C¢digo de retorno=',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_cmd',
                   'Run Command Shell',
                   'Befehlsebene',
                   'Ga naar opdrachtregel',
                   'äÆ¨†≠§≠†Ô ·‚‡Æ™†',
                   'Apre una sessione comandi',
                   '∞ı¶Ê Command Shell',
                   'Session en ligne de commandes',
                   'Abrir indicador de mandatos',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_cmd',             // key use for main popup
                                                // each can used at most once!
                   'C',                         // CTUMWLXR
                   'C',                         // CTAZWLXN
                   'G',                         // GTAOWVSH
                   'R', (* ä *)                 // RTHVWJXG  (* ätêåwéxè *)
                   'C',                         // CTSMWEXR (CTSRWEXR)
                   'C',                         // CTUMWLXR
                   'C',                         // CTDMWLQR
                   'I',                         // ITDMWLSR
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_top',
                   'Run TOP',
                   'Programm TOP aufrufen',
                   'TOP uitvoeren',
                   'á†Ø„·‚®‚Ï TOP',
                   'Lancia il programma TOP',
                   '∞ı¶Ê TOP.EXE',
                   'Lancement de TOP',
                   'Ejecutar TOP',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_top',
                   'T',
                   'T',
                   'T',
                   'T',
                   'T',
                   'T',
                   'T',
                   'T',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_unmount',
                   'Unmount filesystems',
                   'Dateisysteme abmelden',
                   'Afkoppelen bestandssystemen',
                   'ê†ß¨Æ≠‚®‡Æ¢†‚Ï ‰†©´Æ¢Î• ·®·‚•¨Î',
                   'Smonta i file system',
                   '®¯∏¸¿…Æ◊®t≤Œ',
                   'DÇmontage sys. de fichiers',
                   'Desmontar los sistemas de archivos',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_unmount',
                   'U',
                   'A',
                   'A',
                   'H', (* ê *)
                   'S',
                   'U',
                   'D',
                   'D',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_mount',
                   'Remount filesystems',
                   'Dateisysteme zuordnen',
                   'Opnieuw koppelen bestandssystemen',
                   'ë¨Æ≠‚®‡Æ¢†‚Ï ‰†©´Æ¢Î• ·®·‚•¨Î',
                   'Rimonta i file system',
                   '≠´∑s±æ∏¸¿…Æ◊®t≤Œ',
                   'Remontage sys. de fichiers',
                   'Remontar los sistemas de archivos',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_mount',
                   'M',
                   'Z',
                   'O',
                   'V', (* å *)
                   'M', (* was R - duplicate *)
                   'M',
                   'M',
                   'M',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_wpsreset',
                   'Reset WPS',
                   'ArbeitsoberflÑche zurÅcksetzen',
                   'WPS herstarten',
                   'ë°‡Æ· WPS',
                   'Riavvia la WPS',
                   '≠´≥] WPS',
                   'Relancer le WPS',
                   'Reiniciar el WPS',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_wpsreset',
                   'W',
                   'W',
                   'W',
                   'W',
                   'W',
                   'W',
                   'W',
                   'W',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_processlist',
                   'Show window list',
                   'Programmliste anzeigen',
                   'Vensterlijst tonen',
                   'èÆ™†ß†‚Ï ·Ø®·Æ™ Æ™Æ≠',
                   'Mostra l''elenco finestre',
                   '≈„•‹µ¯µ°≤M≥Ê',
                   'Afficher la liste de fenàtres',
                   'Mostrar la lista de ventanas',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_processlist',
                   'L',
                   'L',
                   'V',
                   'J', (* é *)
                   'E',
                   'L',
                   'L',
                   'L',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_esc',
                   'Hide CAD-popup',
                   'MenÅ ausblenden',
                   'Verberg CAD-popup',
                   'ë™‡Î‚Ï CAD-¨•≠Ó',
                   'Nasconde questo menu',
                   '¡Ù¬√ Ctrl-Alt-Del øÔ≥Ê',
                   'Cacher le menu CAD',
                   'Ocultar el men£',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_esc',
                   #27,
                   #27,
                   #27,
                   #27,
                   #27,
                   #27,
                   #27,
                   #27,
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_exit',
                   'Terminate CAD-popup',
                   'MenÅprogramm aus dem Speicher entfernen',
                   'Sluit CAD-popup af',
                   'á†¢•‡Ë®‚Ï CAD-¨•≠Ó',
                   'Termina questo menu',
                   'µ≤ßÙ Ctrl-Alt-Del øÔ≥Ê',
                   'Quitter ce menu',
                   'Salir de este programa',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_exit',
                   'X',
                   'X',
                   'S',
                   'X',
                   'X',
                   'X',
                   'Q',
                   'S',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_reboot',
                   'Reboot System',
                   'System neu starten',
                   'Herstart systeem',
                   'è•‡•ß†£‡„ß®‚Ï ·®·‚•¨„',
                   'Riavvia il sistema',
                   '≠´∑s∂}æ˜',
                   'RedÇmarrer le systäme',
                   'Reiniciar el sistema',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('popup_key_reboot',
                   'R',
                   'N',
                   'H',
                   'G', (* è *)
                   'R',
                   'R',
                   'R',
                   'R',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('CAD_Popup',
                   'CAD-Popup * %1 * please select action > ',
                   'Strg+Alt+Entf-MenÅ * %1 * Bitte wÑhlen Sie eine Funktion > ',
                   'Cad-Popup %1 * Kies a.u.b. een actie > ',
                   'CAD-¨•≠Ó * %1 * èÆ¶†´„©·‚†, ¢Î°•‡®‚• §•©·‚¢®• > ',
                   'Menu Ctrl-Alt-Canc * %1 * Scegliere una funzione > ',
                   'Ctrl-Alt-Del øÔ≥Ê * %1 *°AΩ–øÔæ‹∞ ß@ > ',
                   'Menu Ctrl-Alt-Suppr * %1 * sÇlectionnez une action > ',
                   'Men£ Ctrl-Alt-Supr * %1 * elija una opci¢n > ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('_TOP_EXE_not_found_in_PATH',
                   '%1 was not found in %PATH%.',
                   '%1 wurde nich im Suchfpad %PATH% gefunden.',
                   '%1 is niet gevonden in %PATH%. ',
                   '%1 ≠• ≠†©§•≠ ¢ %PATH%.',
                   'Impossibile trovare %1 in %PATH%.',
                   'µL™k¶b %PATH% §§ß‰®Ï %1 ',
                   '%1 introuvable dans %PATH%.',
                   'No se ha encontrado %1 en %PATH%.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Type_Exit_to_return_to_CAD_popup_',
                   'Type Exit to return to CAD-popup.',
                   'Mit Exit kehren sie zum MenÅ zurÅck.',
                   'Type Exit om terug te keren naar CAD-popup.',
                   'Ç¢•§®‚• EXIT §´Ô ¢Æß¢‡†‚† ¢ CAD-¨•≠Ó.',
                   'Digitare Exit per tornare al menu principale.',
                   'øÈ§J Exit ™¶^ Ctrl-Alt-Del øÔ≥Ê',
                   'Taper Exit pour retourner au menu CAD',
                   'Escriba Exit para volver al men£ Ctrl-Alt-Supr',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_open_CAD_hook_driver__',
                   'Can not open CAD-hook-driver (',
                   'Kann Filtertreiber fÅr Strg+Alt+Entf nicht îffnen (',
                   'Kan het CAD-hook-stuurprogramma niet openen (',
                   'ç•¢Æß¨Æ¶≠Æ Æ‚™‡Î‚Ï §‡†©¢•‡ Ø•‡•Â¢†‚† CAD (',
                   'Impossibile aprire il driver filtro per Ctrl-Alt-Canc (',
                   'µL™k∂}±“ CAD-hook-driver (',
                   'Ouverture impossible du pilote pour Ctrl-Alt-Suppr (',
                   'Imposible abrir controlador de enlace al men£ Ctrl-Alt-Supr (',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Please_install_BaseDev_CADH_SYS',
                   'Please install BaseDev=CADH.SYS',
                   'Bitte fÅgen sie BaseDev=CADH.SYS in die Config.sys ein.',
                   'Installeer a.u.b. BaseDev=CADH.SYS',
                   'èÆ¶†´„©·‚†, „·‚†≠Æ¢®‚• BaseDev=CADH.SYS',
                   'Installare il driver BaseDev=CADH.SYS.',
                   'Ω–•[§J BaseDev=CADH.SYS',
                   'Veuillez installer le pilote BaseDev=CADH.SYS.',
                   'Por favor, instale el controlador BaseDev=CADH.SYS.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Or_maybe_the_program_is_already_running',
                   'Or maybe the program is already running.',
                   'Mîglicherwiese lÑuft dieses Programm schon.',
                   'Of misschien loopt het programma al.',
                   'ÇÆß¨Æ¶≠Æ, Ø‡Æ£‡†¨¨† „¶• ß†Ø„È•≠†.',
                   'Forse il programma ä giÖ stato caricato.',
                   '©Œµ{¶°§w¶b∞ı¶Ê§§°C',
                   'Le programme est peut-àtre en cours d''exÇcution',
                   'O puede que el programa ya se estÇ ejecutando',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_create_event_semaphore__',
                   'Can not create event semaphore (',
                   'Kann Ereignis-Semaphore nicht îffnen (',
                   'Kan event semaphore niet aanmaken (',
                   'ç• „§†´Æ·Ï ·Æß§†‚Ï ·•¨†‰Æ‡ ·Æ°Î‚®Ô (',
                   'Impossibile creare semaforo evento (',
                   'µL™k´ÿ•ﬂ®∆•Û∏πªx (',
                   'CrÇation impossible de l''ÇvÇnement sÇmaphore (',
                   'No pudo crearse el sem†foro de evento (',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_register_CAD_event_semaphore__',
                   'Can not register CAD-event semaphore (',
                   'Kann Ereignissemaphore nicht anmelden (',
                   'Kan CAD-event semaphore niet registreren (',
                   'ç• „§†´Æ·Ï ß†‡•£®·‚‡®‡Æ¢†‚Ï ·•¨†‰Æ‡ ·Æ°Î‚®Ô CAD (',
                   'Impossibile registrare il semaforo evento CAD (',
                   'µL™kµnø˝ Ctrl-Alt-Del ®∆•Û∏πªx (',
                   'Enregistrement impossible de l''ÇvÇnement CAD (',
                   'No pudo registrarse el sem†foro de evento (',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Waiting_for_Ctrl_Alt_Del_____',
                   'Waiting for Ctrl+Alt+Del ... ',
                   'Warte auf Strg+Alt+Entf ... ',
                   'Wacht op Ctrl-Alt-Del ... ',
                   'é¶®§†≠®• Ctrl+Alt+Del...',
                   'In attesa della sequenza Ctrl-Alt-Canc ... ',
                   'µ•´›´ˆ§U Ctrl+Alt+Del §§... ',
                   'En attente de Ctrl-Alt-Suppr',
                   'Esperando Ctrl+Alt+Supr ... ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Waiting_for_SM_Hotkey_____',
                   'Waiting for Hotkey ... ',
                   'Warte auf Tastenkombination ... ',
                   'Wacht op sneltoets ... ',
                   'é¶®§†≠®• ≠†¶†‚®Ô ™Æ¨°®≠†Ê®® ™´†¢®Ë... ',
                   'In attesa della combinazione di tasti impostata ... ',
                   'µ•´›´ˆ§U®œ•Œ™Ã¶€©wºˆ¡‰... ',
                   'En attente du raccourcis clavier... ',
                   'Esperando la tecla r†pida ... ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Waiting_for_Event_____',
                   'Waiting for specified event ... ',
                   'Warte auf Auslîseereignis ... ',
                   'Wacht op systeem gebeurtenis ... ',
                   'é¶®§†≠®• ß†§†≠≠Æ£Æ ·Æ°Î‚®Ô... ',
                   'In attesa dell''evento di sistema impostato ... ',
                   'µ•´›∞ı¶ÊØSÆÌ®∆•Û... ',
                   'En attente de l''ÇvÇnement systäme... ',
                   'Esperando el evento especificado ... ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Can_not_de_register_CAD_event_semaphore__',
                   'Can not de-register CAD-event semaphore (',
                   'Kann Ereignissemaphore nicht abmelden (',
                   'Kan CAD-event semaphore niet de-registreren (',
                   'ç• „§†´Æ·Ï ‡†ß‡•£®·‚‡®‡Æ¢†‚Ï ·•¨†‰Æ‡ ·Æ°Î‚®Ô CAD (',
                   'Impossibile deregistrare il semaforo evento CAD (',
                   'µL™k®˙Æ¯  Ctrl-Alt-Del ®∆•Û∏πªx™∫µnø˝ (',
                   'DÇsenregistrement impossible de l''ÇvÇnement CAD (',
                   'No pudo desregistrarse el sem†foro de evento (',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Presentation_Manager_not_present_can_operate',
                   'Presentation Manager not present, can operate.',
                   'PrÑsentaion-Manager lÑuft nicht, kann nicht starten.',
                   'Presentatie Manager is niet aanwezig, kan niet starten.',
                   'Presentation Manager Æ‚·„‚·‚¢„•‚, ¢ÎØÆ´≠•≠®• ¢Æß¨Æ¶≠Æ.',
                   'Presentation Manager non in funzione, impossibile procedere.',
                   'Presentation Manager §£¶s¶b°A•iæﬁß@°C',
                   'Gestionnaire de PrÇsentation non prÇsent, lancement impossible.',
                   'Imposible operar sin el Presentation Manager.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('can_not_load_cad_pop_mnu',
                   'Can not find file CAD_POP.MNU!',
                   'Die Datei CAD_POP.MNU wurde nicht gefunden!',
                   'Kan bestand CAD_POP.MNU niet vinden!',
                   'ç• „§†´Æ·Ï ≠†©‚® ‰†©´ CAD_POP.MNU!',
                   'Impossibile trovare il file CAD_POP.MNU!',
                   'µL™kß‰®Ï CAD_POP.MNU ¿…°I',
                   'Fichier CAD_POP.MNU introuvable !',
                   '≠Archivo CAD_POP.MNU no encontrado!',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('kann_DOS_SYS_nicht_oeffnen',
                   'Can not open DOS.SYS driver.',
                   'Kann Treiber DOS.SYS nicht îffnen.',
                   'Kan stuurprogramma DOS.SYS niet openen.',
                   'ç• „§†´Æ·Ï Æ‚™‡Î‚Ï §‡†©¢•‡ DOS.SYS.',
                   'Impossibile aprire il driver DOS.SYS.',
                   'µL™k∂}±“ DOS.SYS ≈X∞ µ{¶°°C',
                   'Ouverture du pilote DOS.SYS impossible.',
                   'Imposible abrir el controlador DOS.SYS.',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Line_number_is_invalid',
                   'Line number is invalid: ',
                   'Zeilennummer ungÅltig: ',
                   'Regelnummer is verkeerd: ',
                   'ç•¢•‡≠Î© ≠Æ¨•‡ ·‚‡Æ™®: ',
                   'Numero riga non valido: ',
                   'µLÆƒ™∫¶Ê∏π°G',
                   'NumÇro de ligne incorrect.',
                   'N£mero de l°nea no v†lido: ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Menu_line_already_defined',
                   'Menu line already defined: ',
                   'MenuÅzeile wurde schon definiert: ',
                   'Menuregel is al gedefinieerd: ',
                   'ë‚‡Æ™† ¨•≠Ó „¶• ÆØ‡•§•´•≠†: ',
                   'Riga menu giÖ definita: ',
                   '§w©w∏q™∫øÔ≥Ê¶C°G',
                   'Ligne de menu dÇjÖ dÇfinie : ',
                   'L°nea del men£ ya definida: ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Invalid_menu_definition_for_line',
                   'Invalid menu definition for line ',
                   'UngÅltige MenÅdefinition fÅr Zeile ',
                   'Verkeerde menu definitie voor regel ',
                   'ç•¢•‡≠Æ• ÆØ‡•§•´•≠®• ·‚‡Æ™® ¨•≠Ó ',
                   'Definizione menu non valida alla riga ',
                   '¶π¶Ê™∫øÔ≥Ê©w∏qµLÆƒ ',
                   'DÇfinition de menu incorrecte Ö la ligne ',
                   'Definici¢n no v†lida en el men£ para la l°nea ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('equal_key_used_for_menu_definition_lines',
                   'Equal key used for menu definition lines %1 and %2!',
                   'Es wurden gleiche Tasten fÅr Zeile %1 und %2 vergeben!',
                   'Gelijkteken gebruikt voor menu definitie regels %1 en %2!',
                   'é§≠† ® ‚† ¶• ™´†¢®Ë† ®·ØÆ´ÏßÆ¢†≠† ¢ ·‚‡Æ™†Â ¨•≠Ó %1 ® %2!',
                   'Si ä usato lo stesso tasto per definire le righe %1 e %2!',
                   '%1 §Œ %2 ™∫øÔ≥Ê©w∏q¶C®œ•Œ¨€¶P™∫¡‰≠»°I',
                   'Touches de menu identiques dÇfinies en lignes %1 et %2 !',
                   '≠Se ha usado la misma tecla para el men£ en %1 and %2!',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('Drive_has_open_files_trying_to_unlock_executables',
                   ' Drive %1: has open files, trying to unlock executables...',
                   ' Laufwerk %1: hat offene Dateien, versuche Programmdateien zu laden...',
                   ' Station %1: heeft open bestanden, probeer programma''s te ontgrendelen...',
                   ' ç† §®·™• %1: •·‚Ï Æ‚™‡Î‚Î• ‰†©´Î, Ø‡Æ°„•¨ ‡†ß°´Æ™®‡Æ¢†‚Ï Ø‡Æ£‡†¨¨Î...',
                   ' File aperti sul volume %1:, cerco di sbloccare gli eseguibili ...',
                   ' ∫œ∫– %1: §w¶≥∂}±“™∫¿…Æ◊°A•ø∏’µ€∏—∞£•i∞ı¶Ê¿…Æ◊™∫¬Í©w...',
                   ' Fichiers ouverts sur l''unitÇ %1:. DÇverrouillage des exÇcutables...',
                   ' Hay archivos abiertos en %1:, intentando desbloquear ejecutables...',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('password',
                   'password > ',
                   'Kennwort > ',
                   'wachtwoord > ',
                   'Ø†‡Æ´Ï > ',
                   'parola d''ordine > ',
                   '±KΩX > ',
                   'mot de passe > ',
                   'contrase§a > ',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('ask_yes_no',
                   '`Y`es/`N`o',
                   '`J`a/`N`ein',
                   '`J`a/`N`ee',
                   '`Ñ`†/`ç`•‚', (* da/net *)
                   '`S`ç/`N`o',
                   '¨O(`y`)/ß_°H(`n`)', (* ¨O/ß_°H *)
                   '`O`ui/`N`on',
                   '`S`°/`N`o',
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('key_yes',
                   'y', (* Yes/No *)
                   'j', (* Ja/Nein *)
                   'j', (* Ja/Nee *)
                   'Ñ', (* Ñ†(da)/ç•‚(net) *)
                   's', (* Sç/No *)
                   'y', (* ¨O/ß_°H *)
                   'o', (* Oui/Non *)
                   's', (* Si/No *)
                   '',
                   '',
                   '',
                   '');

  sprach_eintrag12('key_no',
                   'n',
                   'n',
                   'n',
                   'ç',
                   'n',
                   'n',
                   'n',
                   'n',
                   '',
                   '',
                   '',
                   '');


{
  sprach_eintrag12('',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '',
                   '');}

  schreibe_sprach_datei('CAD_POP$.001','CAD_POP$.002','sprach_modul','sprach_start','^string');

end.
